### ISSUE TITLE
Humidity.ino example trouble

### ISSUE THREAD

**Issue by SimonTernoir** [ameltech/sme-hts221-library#1]
Hi, 

The `Humidity.ino` example doesn't seems to work with my SmartEverything Board : 
- Board model : MCS7561-Fox
- sme-hts221-library V1.0.0
- Arduino IDE 1.6.6 (Mac OS X 10.10)

The runtime seems to be stuck at line 17:

``` c++
smeHumidity.begin();
```

Other SE examples are OK (GPS, Ambient Light, etc.)

Any Ideas?

Thx !

**Comment by smkkHw** [comment]
+Seve
Hi thanks for the info we will have a look
On 23 Nov 2015 13:05, Simon notifications@github.com wrote:Hi, 

The Humidity.ino example doesn't seems to work with my SmartEverything Board : 

Board model : MCS7561-Foxsme-hts221-library V1.0.0Arduino IDE 1.6.6 (Mac OS X 10.10)

The runtime seems to be stuck at line 17:

smeHumidity.begin();

Other SE examples are OK (GPS, Ambient Light, etc.)

Any Ideas?

Thx !
