### ISSUE TITLE
readHumidity() not using full 16 bits

### ISSUE THREAD

**Issue by RicoElectrico** [ameltech/sme-hts221-library#4]
By using int we lose a lot of resolution (compare the datasheet). Even though the sensor is not as accurate, it'd be nice to have a bit more resolution, for nicer plots and better calculation of rate of change.

I tried to modify the method myself, but couldn't make any sense of it, besides that it applies some calibration values. The fact that it still outputs integer values even when removing a cast and changing return type baffles me. It's copypasted from readTemperature() which outputs double values, so it should work the same way.

**Comment by searobin** [comment]
Hi Rico.

I've just committed the fix you were looking for.
Now the Humidity returns a double too.

I think the new library version  1.1.2 will be available soon. Otherwise please take the 
one in github.


Ciao

Severino
